### ISSUE TITLE
Update for TSM Core v.4.9.31 (Classic)?

### ISSUE THREAD

**Issue by jerejere** [scrable/TradeSkillMaster_PriceChecker#2]
"An old TSM addon was found installed. Please remove TradeSkillMaster_PriceChecker and any other old TSM addons to avoid issues".

**Comment by scrable** [comment]
I haven't played WoW in a couple years, but doing a quick search through the main TSM addon, the latest version 4.9.31 has a check that searches your current addons and outputs that message if any addon starting with TradeSkillMaster is found. The price checker addon should still function since all TSM is doing is just outputting a message.

To fix this, from within your addons directory, just rename the `TradeSkillMaster_PriceChecker` folder to `TSM_PriceChecker` or something similar. This *should* remove the message, but it is basically a bandaid and not a permanent fix since this is due to TSM and not this addon.

If I get a chance, I will upload a newer version.

**Comment by scrable** [comment]
Closing as I believe this is solved with the above information.

**Comment by jerejere** [comment]
- With folder name TSM_PriceChecker neither WoW or TSM4 doesn't recognize this addon (not listed in AddOns & /tsmpc --> "Type /help for a listing of a few commands")

- Using latest pull with folder name TradeSkillMaster_PriceChecker throws the error (""An old TSM addon was found installed. Please remove TradeSkillMaster_PriceChecker and any other old TSM addons to avoid issues"), but gets recognized (gets listed in AddOns & /tsmpc -->"TradeSkillmaster_PriceChecker: Arguments to ..."

Anyway, it works - just throws that "Old TSM addon" everytime I login.

**Comment by scrable** [comment]
Thank you for your feedback.

My mistake, I forgot to change some other items. It should show up and function now.

https://imgur.com/h6FSvsP

Use the release located here:

https://github.com/scrable/TradeSkillMaster_PriceChecker/releases/tag/v1.12

Please let me know if it works for you!

**Comment by jerejere** [comment]
Not getting the error after logging in in with tagged release 1.12 - Thanks, looking good so far! 

Closing this, opening new issue if i walk into one. Btw made PR for simple ItemId nil check #3
